// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ectfuhflqgfftvktiips.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjdGZ1aGZscWdmZnR2a3RpaXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzcyMjgsImV4cCI6MjA2OTA1MzIyOH0.RjmkOOewNlO2bcJPdDeYnkVfoxPw1teIAn_vr7KE_JU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});